BlowOut/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class AdminController : Controller
    {
        private BlowoutContext db = new BlowoutContext();

        // GET: Admin
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Login user)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (user.Username == "Missouri" && user.Password == "ShowMe")
                {
                    return RedirectToAction("UpdateData");
                }
                else
                {
                    ModelState.AddModelError("Username", "Username or password is incorrect");
                    ModelState.AddModelError("Password", "Username or password is incorrect");
                    return View();
                }
            }
        }

        public ActionResult UpdateData()
        {
            List<FullOrder> allOrders = new List<FullOrder>();
            foreach (Client client in db.Clients.ToList())
            {
                Product product = db.Products.Where(instrument => instrument.instrumentID == client.instrumentID).FirstOrDefault();
                allOrders.Add(new FullOrder
                {
                    ClientID = client.clientID,
                    FirstName = client.firstName,
                    LastName = client.lastName,
                    Address = client.address,
                    City = client.city,
                    State = client.state,
                    Zip = client.zip,
                    Email = client.email,
                    Phone = client.phone,
                    Description = product.desc,
                    Type = product.type,
                    Price = product.price
                });
            }
            return View(allOrders);
        }

        public ActionResult Delete(int[] values)
        {
            if (values != null)
            {
                foreach (int id in values)
                {
                    db.Clients.Remove(db.Clients.Find(id));
                }
                db.SaveChanges();
            }
            return Json(true);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.instrumentID = new SelectList(db.Products, "instrumentID", "desc", client.instrumentID);
            return View(client);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "clientID,firstName,lastName,address,city,state,zip,email,phone,instrumentID")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DisplayAll");
            }
            ViewBag.instrumentID = new SelectList(db.Products, "instrumentID", "desc", client.instrumentID);
            return View(client); ;
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }
    }
}

BlowOut/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class RentalsController : Controller
    {
        private BlowoutContext blowout = new BlowoutContext();

        // GET: Rentals
        public ActionResult Index()
        {
            return View(blowout.Products.ToArray());
        }

        [HttpGet]
        public ActionResult Create(int value)
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clientID,firstName,lastName,address,city,state,zip,email,phone")] Client client, int value)
        {
            if (ModelState.IsValid)
            {
                client.instrumentID = value;
                blowout.Clients.Add(client);
                blowout.SaveChanges();

                List<Product> products = blowout.Products.ToList();
                Product instrument = new Product();
                foreach(Product item in products)
                {
                    if (item.instrumentID == value)
                    {
                        instrument = item;
                    }
                }
                ViewBag.Output += "<h5>Thank you " + client.firstName + " " + client.lastName + " for your purchase</h5>";
                ViewBag.Output += "<h5>Order ID: " + client.clientID + "</h5>";
                ViewBag.Output += "<h5>Instrument Purchased: " + instrument.desc + "</h5>";
                ViewBag.Output += "<h5>Instument Type: " + instrument.type + "</h5>";
                ViewBag.Output += "<h5>Monthly Price: $" + instrument.price + "</h5>";
                ViewBag.Output += "<h5>Total payment after 18 months: $" + instrument.price * 18 + "</h5>";
                ViewBag.Output += "<div style=\"padding-top: 5%;\">";
                ViewBag.Output += "<img style=\"border-radius: 50%;\" src=\"" + instrument.image + "\"/>";
                ViewBag.Output += "</div>";
                return View("Confirmation"); 
            }

            return View(client);
        }
    }
}

BlowOut/Views/Admin/Details.cshtml
@model BlowOut.Models.Client

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Index</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/grayscale.min.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href=@Url.Action("Index", "Home")>BlowOut Musical Instrument Rentals</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Rentals")>Rentals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("About", "Home")>About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Contact", "Home")>Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Admin")>Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="display-page rental-style">
        <div style="padding-top: 10%; padding-bottom: 5%; margin-left: 30px; margin-right: 30px;">
            <div>
                <h4>Order Details</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.firstName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.firstName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.lastName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.lastName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.city)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.city)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.state)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.state)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.zip)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.zip)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.phone)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.phone)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Product.desc)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Product.desc)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Product.type)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Product.type)
                    </dd>
                </dl>
            </div>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.clientID }) |
                @Html.ActionLink("Back to List", "UpdateData")
            </p>
        </div>
    </section>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Content/js/grayscale.min.js"></script>
</body>

BlowOut/Views/Admin/DisplayAll.cshtml
@using BlowOut.Models
@model IEnumerable<FullOrder>

@{
    ViewBag.Title = "Display All Orders";
    Layout = null;
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Index</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/grayscale.min.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Content/main.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href=@Url.Action("Index", "Home")>BlowOut Musical Instrument Rentals</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Rentals")>Rentals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("About", "Home")>About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Contact", "Home")>Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Admin")>Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="display-page rental-style">
        <div style="padding-top: 10%; padding-bottom: 5%; margin-left: 30px; margin-right: 30px;">
            <div class="datatable-container">
                <h2 style="padding-top: 20px; padding-left: 20px;">Order Details</h2>
                <div style="padding-top: 20px; padding-left: 20px;">
                    <hr />
                    <table class="table">
                        <tr style="font-size: 12px; color: white;">
                            <th>Order ID</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Address</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Zip</th>
                            <th>Email Address</th>
                            <th>Phone Number</th>
                            <th>Instrument</th>
                            <th>New/Used</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                        @foreach (FullOrder fullOrder in Model)
                        {
                            <tr class="table-row" style="font-size: 12px; color: white;">
                                <td>@fullOrder.ClientID</td>
                                <td>@fullOrder.FirstName</td>
                                <td>@fullOrder.LastName</td>
                                <td>@fullOrder.Address</td>
                                <td>@fullOrder.City</td>
                                <td>@fullOrder.State</td>
                                <td>@fullOrder.Zip</td>
                                <td>@fullOrder.Email</td>
                                <td>@fullOrder.Phone</td>
                                <td>@fullOrder.Description</td>
                                <td>@fullOrder.Type</td>
                                <td>@fullOrder.Price</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = fullOrder.ClientID }) |
                                    @Html.ActionLink("Details", "Details", new { id = fullOrder.ClientID })
                                </td>
                            </tr>
                        }
                    </table>
                    <button id="button" style="margin-top: 20px; margin-bottom: 30px;" class="btn btn-primary btn-sm">Delete Selected Orders</button>
                </div>
            </div>
        </div>
    </section>
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Content/js/grayscale.min.js"></script>
</body>

BlowOut/Views/Admin/Edit.cshtml
@model BlowOut.Models.Client

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Index</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/grayscale.min.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Content/main.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href=@Url.Action("Index", "Home")>BlowOut Musical Instrument Rentals</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Rentals")>Rentals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("About", "Home")>About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Contact", "Home")>Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Admin")>Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="display-page rental-style">
        <div style="padding-top: 10%; padding-bottom: 5%; margin-left: 30px; margin-right: 30px;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div style="width: 30%;" class="form-horizontal">
                    <h4 style="padding-left: 15px;">Edit Client Information</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.clientID)

                    <div class="form-group">
                        <div class="col-md-10">
                            First Name
                            @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            Last Name
                            @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            Street Address
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            City
                            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            State
                            @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            Zip Code
                            @Html.EditorFor(model => model.zip, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.zip, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            Email Address
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            Phone Number
                            @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            Instrument Purchased
                            @Html.DropDownList("instrumentID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.instrumentID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
            <div style="padding-left: 15px;">
                @Html.ActionLink("Back to List", "UpdateData")
            </div>
        </div>
        
    </section>
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Content/js/grayscale.min.js"></script>
</body>

BlowOut/Views/Admin/Index.cshtml
@model BlowOut.Models.Login
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Index</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/grayscale.min.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href=@Url.Action("Index", "Home")>BlowOut Musical Instrument Rentals</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Rentals")>Rentals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("About", "Home")>About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Contact", "Home")>Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href=@Url.Action("Index", "Admin")>Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="admin-page-index rental-style" style="min-height: 61rem; background-image: url(../Content/admin.jpg); background-size: cover; background-repeat: repeat;">
        <div div class="rental-background" style="padding-left: 10%; height: 100%; padding-top: 8%; padding-bottom: 5%;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal" style="padding-left: 30px;">
                    <h4 style="margin-left: 20px;">Authenticate Login Information</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group form-fifty">
                        <label class="control-label form-title">Username</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Username", style = "width: 50%;" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group form-fifty">
                        <label class="control-label form-title">Password</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password", style = "width: 50%;" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group form-fifty">
                        <div class="col-md-offset-2 col-md-10" style="padding-top: 20px; padding-bottom: 40px;">
                            <input type="submit" value="Submit" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/Content/js/grayscale.min.js"></script>
</body>
</html>